version: '3.3'  
services: 
  web-client: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "5000:5000" 
    depends_on:
      - service-db 
    environment:
      - DATABASE_HOST=service-db  
  service-db: 
    image: postgres:latest 
    environment: 
      POSTGRES_DB: mydatabase 
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
    ports:
      - "5432:5432" 
    volumes:
     - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
     - db-data:/var/lib/postgresql/data 
    restart: unless-stopped  
  pgadmin: 
    image: dpage/pgadmin4:latest 
    restart: always 
    ports:
      - "8080:80" 
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@example.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    depends_on:
      - service-db 
    volumes: 
      - pgadmin-data:/var/lib/pgadmin  
volumes: 
  db-data: 
  pgadmin-data: 