# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  # Имя виртуальной машины
  config.vm.define "jenkins"
  
  # Используемый образ
  config.vm.box = "ubuntu/focal64"
  
  # Используемый репозиторий для образов
  config.vm.box_url = "https://vagrant.elab.pro/ubuntu/focal64"
  
  # Отключение GUI
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = "4096"
  end

  # Переадресация портов
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Синхронизация директорий
  config.vm.synced_folder ".", "/mnt/host_machine"

  # Скрипт для пост-установки
  config.vm.provision "shell", path: "provision.sh"
end
